import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UnAuthNav from "@/components/UnAuthNav";
import AuthNav from "@/components/AuthNav";
import { MyContextProvider } from "@/context/MyContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const auth = false

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
        <Toaster position="top-center" reverseOrder={false} />


        <MyContextProvider>
         <UnAuthNav className="flex " /> 
          {children}
        </MyContextProvider>
      </body>
    </html>
  );
}
